# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='agent.proto',
  package='agent',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x61gent.proto\x12\x05\x61gent\"^\n\tDatapoint\x12\x0e\n\x06stream\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12 \n\x04type\x18\x03 \x01(\x0e\x32\x12.agent.ContentType\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\"\x14\n\x12StreamDataResponse\"\x12\n\x10PostDataResponse\"\x15\n\x13GetROSTopicsRequest\"\x1a\n\x18RegisterROSTopicResponse\"&\n\x14GetROSTopicsResponse\x12\x0e\n\x06topics\x18\x01 \x03(\t\"W\n\x08ROSTopic\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tdata_type\x18\x02 \x01(\t\x12\x10\n\x08msg_desc\x18\x03 \x01(\t\x12\x18\n\x04tags\x18\x04 \x03(\x0b\x32\n.agent.Tag\"!\n\x03Tag\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t*r\n\x0b\x43ontentType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04TEXT\x10\x01\x12\x0b\n\x07NUMERIC\x10\x02\x12\x07\n\x03PNG\x10\x03\x12\x08\n\x04JPEG\x10\x04\x12\t\n\x05VIDEO\x10\x05\x12\x08\n\x04\x46ILE\x10\x06\x12\x0e\n\nPOINTCLOUD\x10\x07\x12\x07\n\x03ROS\x10\x0b\x32\x92\x02\n\x05\x41gent\x12=\n\nStreamData\x12\x10.agent.Datapoint\x1a\x19.agent.StreamDataResponse\"\x00(\x01\x12\x37\n\x08PostData\x12\x10.agent.Datapoint\x1a\x17.agent.PostDataResponse\"\x00\x12\x46\n\x10RegisterROSTopic\x12\x0f.agent.ROSTopic\x1a\x1f.agent.RegisterROSTopicResponse\"\x00\x12I\n\x0cGetROSTopics\x12\x1a.agent.GetROSTopicsRequest\x1a\x1b.agent.GetROSTopicsResponse\"\x00\x62\x06proto3')
)

_CONTENTTYPE = _descriptor.EnumDescriptor(
  name='ContentType',
  full_name='agent.ContentType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEXT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NUMERIC', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PNG', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JPEG', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VIDEO', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FILE', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POINTCLOUD', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROS', index=8, number=11,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=375,
  serialized_end=489,
)
_sym_db.RegisterEnumDescriptor(_CONTENTTYPE)

ContentType = enum_type_wrapper.EnumTypeWrapper(_CONTENTTYPE)
UNKNOWN = 0
TEXT = 1
NUMERIC = 2
PNG = 3
JPEG = 4
VIDEO = 5
FILE = 6
POINTCLOUD = 7
ROS = 11



_DATAPOINT = _descriptor.Descriptor(
  name='Datapoint',
  full_name='agent.Datapoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream', full_name='agent.Datapoint.stream', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='agent.Datapoint.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='agent.Datapoint.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='agent.Datapoint.data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=116,
)


_STREAMDATARESPONSE = _descriptor.Descriptor(
  name='StreamDataResponse',
  full_name='agent.StreamDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=138,
)


_POSTDATARESPONSE = _descriptor.Descriptor(
  name='PostDataResponse',
  full_name='agent.PostDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=158,
)


_GETROSTOPICSREQUEST = _descriptor.Descriptor(
  name='GetROSTopicsRequest',
  full_name='agent.GetROSTopicsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=181,
)


_REGISTERROSTOPICRESPONSE = _descriptor.Descriptor(
  name='RegisterROSTopicResponse',
  full_name='agent.RegisterROSTopicResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=209,
)


_GETROSTOPICSRESPONSE = _descriptor.Descriptor(
  name='GetROSTopicsResponse',
  full_name='agent.GetROSTopicsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topics', full_name='agent.GetROSTopicsResponse.topics', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=249,
)


_ROSTOPIC = _descriptor.Descriptor(
  name='ROSTopic',
  full_name='agent.ROSTopic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='agent.ROSTopic.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_type', full_name='agent.ROSTopic.data_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_desc', full_name='agent.ROSTopic.msg_desc', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tags', full_name='agent.ROSTopic.tags', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=338,
)


_TAG = _descriptor.Descriptor(
  name='Tag',
  full_name='agent.Tag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='agent.Tag.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='agent.Tag.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=373,
)

_DATAPOINT.fields_by_name['type'].enum_type = _CONTENTTYPE
_ROSTOPIC.fields_by_name['tags'].message_type = _TAG
DESCRIPTOR.message_types_by_name['Datapoint'] = _DATAPOINT
DESCRIPTOR.message_types_by_name['StreamDataResponse'] = _STREAMDATARESPONSE
DESCRIPTOR.message_types_by_name['PostDataResponse'] = _POSTDATARESPONSE
DESCRIPTOR.message_types_by_name['GetROSTopicsRequest'] = _GETROSTOPICSREQUEST
DESCRIPTOR.message_types_by_name['RegisterROSTopicResponse'] = _REGISTERROSTOPICRESPONSE
DESCRIPTOR.message_types_by_name['GetROSTopicsResponse'] = _GETROSTOPICSRESPONSE
DESCRIPTOR.message_types_by_name['ROSTopic'] = _ROSTOPIC
DESCRIPTOR.message_types_by_name['Tag'] = _TAG
DESCRIPTOR.enum_types_by_name['ContentType'] = _CONTENTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Datapoint = _reflection.GeneratedProtocolMessageType('Datapoint', (_message.Message,), dict(
  DESCRIPTOR = _DATAPOINT,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:agent.Datapoint)
  ))
_sym_db.RegisterMessage(Datapoint)

StreamDataResponse = _reflection.GeneratedProtocolMessageType('StreamDataResponse', (_message.Message,), dict(
  DESCRIPTOR = _STREAMDATARESPONSE,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:agent.StreamDataResponse)
  ))
_sym_db.RegisterMessage(StreamDataResponse)

PostDataResponse = _reflection.GeneratedProtocolMessageType('PostDataResponse', (_message.Message,), dict(
  DESCRIPTOR = _POSTDATARESPONSE,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:agent.PostDataResponse)
  ))
_sym_db.RegisterMessage(PostDataResponse)

GetROSTopicsRequest = _reflection.GeneratedProtocolMessageType('GetROSTopicsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETROSTOPICSREQUEST,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:agent.GetROSTopicsRequest)
  ))
_sym_db.RegisterMessage(GetROSTopicsRequest)

RegisterROSTopicResponse = _reflection.GeneratedProtocolMessageType('RegisterROSTopicResponse', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERROSTOPICRESPONSE,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:agent.RegisterROSTopicResponse)
  ))
_sym_db.RegisterMessage(RegisterROSTopicResponse)

GetROSTopicsResponse = _reflection.GeneratedProtocolMessageType('GetROSTopicsResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETROSTOPICSRESPONSE,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:agent.GetROSTopicsResponse)
  ))
_sym_db.RegisterMessage(GetROSTopicsResponse)

ROSTopic = _reflection.GeneratedProtocolMessageType('ROSTopic', (_message.Message,), dict(
  DESCRIPTOR = _ROSTOPIC,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:agent.ROSTopic)
  ))
_sym_db.RegisterMessage(ROSTopic)

Tag = _reflection.GeneratedProtocolMessageType('Tag', (_message.Message,), dict(
  DESCRIPTOR = _TAG,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:agent.Tag)
  ))
_sym_db.RegisterMessage(Tag)



_AGENT = _descriptor.ServiceDescriptor(
  name='Agent',
  full_name='agent.Agent',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=492,
  serialized_end=766,
  methods=[
  _descriptor.MethodDescriptor(
    name='StreamData',
    full_name='agent.Agent.StreamData',
    index=0,
    containing_service=None,
    input_type=_DATAPOINT,
    output_type=_STREAMDATARESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PostData',
    full_name='agent.Agent.PostData',
    index=1,
    containing_service=None,
    input_type=_DATAPOINT,
    output_type=_POSTDATARESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RegisterROSTopic',
    full_name='agent.Agent.RegisterROSTopic',
    index=2,
    containing_service=None,
    input_type=_ROSTOPIC,
    output_type=_REGISTERROSTOPICRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetROSTopics',
    full_name='agent.Agent.GetROSTopics',
    index=3,
    containing_service=None,
    input_type=_GETROSTOPICSREQUEST,
    output_type=_GETROSTOPICSRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AGENT)

DESCRIPTOR.services_by_name['Agent'] = _AGENT

# @@protoc_insertion_point(module_scope)
