[formant]
agent-server-port-grpc = "5501"
agent-server-port-http = "5502"
agent-server-ip = "localhost"

#### ROS Global configuration ####

[ros]
# the name of a common reference frame relative to which any ROS messages associated with a `frame_id` will be expressed
world-reference-frame-id = "world_frame"

[tags]
site = "san_francisco_1"
environment = "dev"
group = "engineering"

##### Basic Streams #####

[[streams]]
name = "stream.001"

##### Watch Streams #####

[[streams]]
name = "cognex.001"
dir = "/home/ftp/upload"
formant-type = "image"
ext = ".jpg"

[[streams]]
name = "test.log"
filename = "/home/logs/test.log"
file-format = "json"
time-key = "timestamp"
time-format = "2006-01-02T15:04:05Z07:00"

##### ROS Streams #####

[[streams]]
name = "turtle.cmd_vel"
ros-topic = "/turtle1/cmd_vel"

[[streams]]
name = "abb.joint_1.position"
ros-topic = "/joint_states/joint_1"
ros-path = "data"

[[streams]]
name = "robot.localization.001"
ros-odom-topic = "/odom"
ros-map-topic = "/map"
