# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/model/v1/text.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aprotos/model/v1/text.proto\x12\x08v1.model\"\x1c\n\x04Text\x12\x14\n\x05value\x18\x01 \x01(\tR\x05value\"\x1c\n\x04Json\x12\x14\n\x05value\x18\x01 \x01(\tR\x05valueB+Z)github.com/FormantIO/genproto/go/v1/modelb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.model.v1.text_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z)github.com/FormantIO/genproto/go/v1/model'
  _TEXT._serialized_start=40
  _TEXT._serialized_end=68
  _JSON._serialized_start=70
  _JSON._serialized_end=98
# @@protoc_insertion_point(module_scope)
