// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: protos/model/v1/intervention.proto

#include "protos/model/v1/intervention.pb.h"
#include "protos/model/v1/intervention.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/sync_stream.h>
#include <gmock/gmock.h>
namespace v1 {
namespace model {

} // namespace v1
} // namespace model

