// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/agent/v1/agent.proto

#ifndef PROTOBUF_INCLUDED_protos_2fagent_2fv1_2fagent_2eproto
#define PROTOBUF_INCLUDED_protos_2fagent_2fv1_2fagent_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "protos/model/v1/datapoint.pb.h"
#include "protos/model/v1/intervention.pb.h"
#include "protos/model/v1/ros.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_protos_2fagent_2fv1_2fagent_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_protos_2fagent_2fv1_2fagent_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[11]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_protos_2fagent_2fv1_2fagent_2eproto();
namespace v1 {
namespace agent {
class GetInterventionRequestRequest;
class GetInterventionRequestRequestDefaultTypeInternal;
extern GetInterventionRequestRequestDefaultTypeInternal _GetInterventionRequestRequest_default_instance_;
class GetInterventionResponseRequest;
class GetInterventionResponseRequestDefaultTypeInternal;
extern GetInterventionResponseRequestDefaultTypeInternal _GetInterventionResponseRequest_default_instance_;
class GetROSTopicsRequest;
class GetROSTopicsRequestDefaultTypeInternal;
extern GetROSTopicsRequestDefaultTypeInternal _GetROSTopicsRequest_default_instance_;
class GetROSTopicsResponse;
class GetROSTopicsResponseDefaultTypeInternal;
extern GetROSTopicsResponseDefaultTypeInternal _GetROSTopicsResponse_default_instance_;
class GetROSTopicsSubscriptionConfigRequest;
class GetROSTopicsSubscriptionConfigRequestDefaultTypeInternal;
extern GetROSTopicsSubscriptionConfigRequestDefaultTypeInternal _GetROSTopicsSubscriptionConfigRequest_default_instance_;
class GetROSTopicsSubscriptionConfigResponse;
class GetROSTopicsSubscriptionConfigResponseDefaultTypeInternal;
extern GetROSTopicsSubscriptionConfigResponseDefaultTypeInternal _GetROSTopicsSubscriptionConfigResponse_default_instance_;
class GetROSWorldReferenceFrameIDRequest;
class GetROSWorldReferenceFrameIDRequestDefaultTypeInternal;
extern GetROSWorldReferenceFrameIDRequestDefaultTypeInternal _GetROSWorldReferenceFrameIDRequest_default_instance_;
class GetROSWorldReferenceFrameIDResponse;
class GetROSWorldReferenceFrameIDResponseDefaultTypeInternal;
extern GetROSWorldReferenceFrameIDResponseDefaultTypeInternal _GetROSWorldReferenceFrameIDResponse_default_instance_;
class PostDataResponse;
class PostDataResponseDefaultTypeInternal;
extern PostDataResponseDefaultTypeInternal _PostDataResponse_default_instance_;
class RegisterROSTopicResponse;
class RegisterROSTopicResponseDefaultTypeInternal;
extern RegisterROSTopicResponseDefaultTypeInternal _RegisterROSTopicResponse_default_instance_;
class StreamDataResponse;
class StreamDataResponseDefaultTypeInternal;
extern StreamDataResponseDefaultTypeInternal _StreamDataResponse_default_instance_;
}  // namespace agent
}  // namespace v1
namespace google {
namespace protobuf {
template<> ::v1::agent::GetInterventionRequestRequest* Arena::CreateMaybeMessage<::v1::agent::GetInterventionRequestRequest>(Arena*);
template<> ::v1::agent::GetInterventionResponseRequest* Arena::CreateMaybeMessage<::v1::agent::GetInterventionResponseRequest>(Arena*);
template<> ::v1::agent::GetROSTopicsRequest* Arena::CreateMaybeMessage<::v1::agent::GetROSTopicsRequest>(Arena*);
template<> ::v1::agent::GetROSTopicsResponse* Arena::CreateMaybeMessage<::v1::agent::GetROSTopicsResponse>(Arena*);
template<> ::v1::agent::GetROSTopicsSubscriptionConfigRequest* Arena::CreateMaybeMessage<::v1::agent::GetROSTopicsSubscriptionConfigRequest>(Arena*);
template<> ::v1::agent::GetROSTopicsSubscriptionConfigResponse* Arena::CreateMaybeMessage<::v1::agent::GetROSTopicsSubscriptionConfigResponse>(Arena*);
template<> ::v1::agent::GetROSWorldReferenceFrameIDRequest* Arena::CreateMaybeMessage<::v1::agent::GetROSWorldReferenceFrameIDRequest>(Arena*);
template<> ::v1::agent::GetROSWorldReferenceFrameIDResponse* Arena::CreateMaybeMessage<::v1::agent::GetROSWorldReferenceFrameIDResponse>(Arena*);
template<> ::v1::agent::PostDataResponse* Arena::CreateMaybeMessage<::v1::agent::PostDataResponse>(Arena*);
template<> ::v1::agent::RegisterROSTopicResponse* Arena::CreateMaybeMessage<::v1::agent::RegisterROSTopicResponse>(Arena*);
template<> ::v1::agent::StreamDataResponse* Arena::CreateMaybeMessage<::v1::agent::StreamDataResponse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace v1 {
namespace agent {

// ===================================================================

class StreamDataResponse final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:v1.agent.StreamDataResponse) */ {
 public:
  StreamDataResponse();
  virtual ~StreamDataResponse();

  StreamDataResponse(const StreamDataResponse& from);

  inline StreamDataResponse& operator=(const StreamDataResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StreamDataResponse(StreamDataResponse&& from) noexcept
    : StreamDataResponse() {
    *this = ::std::move(from);
  }

  inline StreamDataResponse& operator=(StreamDataResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const StreamDataResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StreamDataResponse* internal_default_instance() {
    return reinterpret_cast<const StreamDataResponse*>(
               &_StreamDataResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(StreamDataResponse* other);
  friend void swap(StreamDataResponse& a, StreamDataResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StreamDataResponse* New() const final {
    return CreateMaybeMessage<StreamDataResponse>(nullptr);
  }

  StreamDataResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<StreamDataResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const StreamDataResponse& from);
  void MergeFrom(const StreamDataResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StreamDataResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:v1.agent.StreamDataResponse)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protos_2fagent_2fv1_2fagent_2eproto;
};
// -------------------------------------------------------------------

class PostDataResponse final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:v1.agent.PostDataResponse) */ {
 public:
  PostDataResponse();
  virtual ~PostDataResponse();

  PostDataResponse(const PostDataResponse& from);

  inline PostDataResponse& operator=(const PostDataResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PostDataResponse(PostDataResponse&& from) noexcept
    : PostDataResponse() {
    *this = ::std::move(from);
  }

  inline PostDataResponse& operator=(PostDataResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const PostDataResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PostDataResponse* internal_default_instance() {
    return reinterpret_cast<const PostDataResponse*>(
               &_PostDataResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(PostDataResponse* other);
  friend void swap(PostDataResponse& a, PostDataResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PostDataResponse* New() const final {
    return CreateMaybeMessage<PostDataResponse>(nullptr);
  }

  PostDataResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PostDataResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PostDataResponse& from);
  void MergeFrom(const PostDataResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PostDataResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:v1.agent.PostDataResponse)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protos_2fagent_2fv1_2fagent_2eproto;
};
// -------------------------------------------------------------------

class RegisterROSTopicResponse final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:v1.agent.RegisterROSTopicResponse) */ {
 public:
  RegisterROSTopicResponse();
  virtual ~RegisterROSTopicResponse();

  RegisterROSTopicResponse(const RegisterROSTopicResponse& from);

  inline RegisterROSTopicResponse& operator=(const RegisterROSTopicResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RegisterROSTopicResponse(RegisterROSTopicResponse&& from) noexcept
    : RegisterROSTopicResponse() {
    *this = ::std::move(from);
  }

  inline RegisterROSTopicResponse& operator=(RegisterROSTopicResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const RegisterROSTopicResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RegisterROSTopicResponse* internal_default_instance() {
    return reinterpret_cast<const RegisterROSTopicResponse*>(
               &_RegisterROSTopicResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(RegisterROSTopicResponse* other);
  friend void swap(RegisterROSTopicResponse& a, RegisterROSTopicResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RegisterROSTopicResponse* New() const final {
    return CreateMaybeMessage<RegisterROSTopicResponse>(nullptr);
  }

  RegisterROSTopicResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RegisterROSTopicResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RegisterROSTopicResponse& from);
  void MergeFrom(const RegisterROSTopicResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RegisterROSTopicResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:v1.agent.RegisterROSTopicResponse)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protos_2fagent_2fv1_2fagent_2eproto;
};
// -------------------------------------------------------------------

class GetROSTopicsRequest final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:v1.agent.GetROSTopicsRequest) */ {
 public:
  GetROSTopicsRequest();
  virtual ~GetROSTopicsRequest();

  GetROSTopicsRequest(const GetROSTopicsRequest& from);

  inline GetROSTopicsRequest& operator=(const GetROSTopicsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetROSTopicsRequest(GetROSTopicsRequest&& from) noexcept
    : GetROSTopicsRequest() {
    *this = ::std::move(from);
  }

  inline GetROSTopicsRequest& operator=(GetROSTopicsRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const GetROSTopicsRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetROSTopicsRequest* internal_default_instance() {
    return reinterpret_cast<const GetROSTopicsRequest*>(
               &_GetROSTopicsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(GetROSTopicsRequest* other);
  friend void swap(GetROSTopicsRequest& a, GetROSTopicsRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetROSTopicsRequest* New() const final {
    return CreateMaybeMessage<GetROSTopicsRequest>(nullptr);
  }

  GetROSTopicsRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GetROSTopicsRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GetROSTopicsRequest& from);
  void MergeFrom(const GetROSTopicsRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetROSTopicsRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:v1.agent.GetROSTopicsRequest)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protos_2fagent_2fv1_2fagent_2eproto;
};
// -------------------------------------------------------------------

class GetROSTopicsResponse final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:v1.agent.GetROSTopicsResponse) */ {
 public:
  GetROSTopicsResponse();
  virtual ~GetROSTopicsResponse();

  GetROSTopicsResponse(const GetROSTopicsResponse& from);

  inline GetROSTopicsResponse& operator=(const GetROSTopicsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetROSTopicsResponse(GetROSTopicsResponse&& from) noexcept
    : GetROSTopicsResponse() {
    *this = ::std::move(from);
  }

  inline GetROSTopicsResponse& operator=(GetROSTopicsResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const GetROSTopicsResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetROSTopicsResponse* internal_default_instance() {
    return reinterpret_cast<const GetROSTopicsResponse*>(
               &_GetROSTopicsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(GetROSTopicsResponse* other);
  friend void swap(GetROSTopicsResponse& a, GetROSTopicsResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetROSTopicsResponse* New() const final {
    return CreateMaybeMessage<GetROSTopicsResponse>(nullptr);
  }

  GetROSTopicsResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GetROSTopicsResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GetROSTopicsResponse& from);
  void MergeFrom(const GetROSTopicsResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetROSTopicsResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string topics = 1;
  int topics_size() const;
  void clear_topics();
  static const int kTopicsFieldNumber = 1;
  const ::std::string& topics(int index) const;
  ::std::string* mutable_topics(int index);
  void set_topics(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_topics(int index, ::std::string&& value);
  #endif
  void set_topics(int index, const char* value);
  void set_topics(int index, const char* value, size_t size);
  ::std::string* add_topics();
  void add_topics(const ::std::string& value);
  #if LANG_CXX11
  void add_topics(::std::string&& value);
  #endif
  void add_topics(const char* value);
  void add_topics(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField<::std::string>& topics() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* mutable_topics();

  // @@protoc_insertion_point(class_scope:v1.agent.GetROSTopicsResponse)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField<::std::string> topics_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protos_2fagent_2fv1_2fagent_2eproto;
};
// -------------------------------------------------------------------

class GetROSTopicsSubscriptionConfigRequest final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:v1.agent.GetROSTopicsSubscriptionConfigRequest) */ {
 public:
  GetROSTopicsSubscriptionConfigRequest();
  virtual ~GetROSTopicsSubscriptionConfigRequest();

  GetROSTopicsSubscriptionConfigRequest(const GetROSTopicsSubscriptionConfigRequest& from);

  inline GetROSTopicsSubscriptionConfigRequest& operator=(const GetROSTopicsSubscriptionConfigRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetROSTopicsSubscriptionConfigRequest(GetROSTopicsSubscriptionConfigRequest&& from) noexcept
    : GetROSTopicsSubscriptionConfigRequest() {
    *this = ::std::move(from);
  }

  inline GetROSTopicsSubscriptionConfigRequest& operator=(GetROSTopicsSubscriptionConfigRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const GetROSTopicsSubscriptionConfigRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetROSTopicsSubscriptionConfigRequest* internal_default_instance() {
    return reinterpret_cast<const GetROSTopicsSubscriptionConfigRequest*>(
               &_GetROSTopicsSubscriptionConfigRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(GetROSTopicsSubscriptionConfigRequest* other);
  friend void swap(GetROSTopicsSubscriptionConfigRequest& a, GetROSTopicsSubscriptionConfigRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetROSTopicsSubscriptionConfigRequest* New() const final {
    return CreateMaybeMessage<GetROSTopicsSubscriptionConfigRequest>(nullptr);
  }

  GetROSTopicsSubscriptionConfigRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GetROSTopicsSubscriptionConfigRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GetROSTopicsSubscriptionConfigRequest& from);
  void MergeFrom(const GetROSTopicsSubscriptionConfigRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetROSTopicsSubscriptionConfigRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:v1.agent.GetROSTopicsSubscriptionConfigRequest)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protos_2fagent_2fv1_2fagent_2eproto;
};
// -------------------------------------------------------------------

class GetROSTopicsSubscriptionConfigResponse final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:v1.agent.GetROSTopicsSubscriptionConfigResponse) */ {
 public:
  GetROSTopicsSubscriptionConfigResponse();
  virtual ~GetROSTopicsSubscriptionConfigResponse();

  GetROSTopicsSubscriptionConfigResponse(const GetROSTopicsSubscriptionConfigResponse& from);

  inline GetROSTopicsSubscriptionConfigResponse& operator=(const GetROSTopicsSubscriptionConfigResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetROSTopicsSubscriptionConfigResponse(GetROSTopicsSubscriptionConfigResponse&& from) noexcept
    : GetROSTopicsSubscriptionConfigResponse() {
    *this = ::std::move(from);
  }

  inline GetROSTopicsSubscriptionConfigResponse& operator=(GetROSTopicsSubscriptionConfigResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const GetROSTopicsSubscriptionConfigResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetROSTopicsSubscriptionConfigResponse* internal_default_instance() {
    return reinterpret_cast<const GetROSTopicsSubscriptionConfigResponse*>(
               &_GetROSTopicsSubscriptionConfigResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(GetROSTopicsSubscriptionConfigResponse* other);
  friend void swap(GetROSTopicsSubscriptionConfigResponse& a, GetROSTopicsSubscriptionConfigResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetROSTopicsSubscriptionConfigResponse* New() const final {
    return CreateMaybeMessage<GetROSTopicsSubscriptionConfigResponse>(nullptr);
  }

  GetROSTopicsSubscriptionConfigResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GetROSTopicsSubscriptionConfigResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GetROSTopicsSubscriptionConfigResponse& from);
  void MergeFrom(const GetROSTopicsSubscriptionConfigResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetROSTopicsSubscriptionConfigResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .v1.model.ROSTopicSubscriptionConfig topics = 1;
  int topics_size() const;
  void clear_topics();
  static const int kTopicsFieldNumber = 1;
  ::v1::model::ROSTopicSubscriptionConfig* mutable_topics(int index);
  ::google::protobuf::RepeatedPtrField< ::v1::model::ROSTopicSubscriptionConfig >*
      mutable_topics();
  const ::v1::model::ROSTopicSubscriptionConfig& topics(int index) const;
  ::v1::model::ROSTopicSubscriptionConfig* add_topics();
  const ::google::protobuf::RepeatedPtrField< ::v1::model::ROSTopicSubscriptionConfig >&
      topics() const;

  // @@protoc_insertion_point(class_scope:v1.agent.GetROSTopicsSubscriptionConfigResponse)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::v1::model::ROSTopicSubscriptionConfig > topics_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protos_2fagent_2fv1_2fagent_2eproto;
};
// -------------------------------------------------------------------

class GetROSWorldReferenceFrameIDRequest final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:v1.agent.GetROSWorldReferenceFrameIDRequest) */ {
 public:
  GetROSWorldReferenceFrameIDRequest();
  virtual ~GetROSWorldReferenceFrameIDRequest();

  GetROSWorldReferenceFrameIDRequest(const GetROSWorldReferenceFrameIDRequest& from);

  inline GetROSWorldReferenceFrameIDRequest& operator=(const GetROSWorldReferenceFrameIDRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetROSWorldReferenceFrameIDRequest(GetROSWorldReferenceFrameIDRequest&& from) noexcept
    : GetROSWorldReferenceFrameIDRequest() {
    *this = ::std::move(from);
  }

  inline GetROSWorldReferenceFrameIDRequest& operator=(GetROSWorldReferenceFrameIDRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const GetROSWorldReferenceFrameIDRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetROSWorldReferenceFrameIDRequest* internal_default_instance() {
    return reinterpret_cast<const GetROSWorldReferenceFrameIDRequest*>(
               &_GetROSWorldReferenceFrameIDRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(GetROSWorldReferenceFrameIDRequest* other);
  friend void swap(GetROSWorldReferenceFrameIDRequest& a, GetROSWorldReferenceFrameIDRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetROSWorldReferenceFrameIDRequest* New() const final {
    return CreateMaybeMessage<GetROSWorldReferenceFrameIDRequest>(nullptr);
  }

  GetROSWorldReferenceFrameIDRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GetROSWorldReferenceFrameIDRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GetROSWorldReferenceFrameIDRequest& from);
  void MergeFrom(const GetROSWorldReferenceFrameIDRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetROSWorldReferenceFrameIDRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:v1.agent.GetROSWorldReferenceFrameIDRequest)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protos_2fagent_2fv1_2fagent_2eproto;
};
// -------------------------------------------------------------------

class GetROSWorldReferenceFrameIDResponse final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:v1.agent.GetROSWorldReferenceFrameIDResponse) */ {
 public:
  GetROSWorldReferenceFrameIDResponse();
  virtual ~GetROSWorldReferenceFrameIDResponse();

  GetROSWorldReferenceFrameIDResponse(const GetROSWorldReferenceFrameIDResponse& from);

  inline GetROSWorldReferenceFrameIDResponse& operator=(const GetROSWorldReferenceFrameIDResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetROSWorldReferenceFrameIDResponse(GetROSWorldReferenceFrameIDResponse&& from) noexcept
    : GetROSWorldReferenceFrameIDResponse() {
    *this = ::std::move(from);
  }

  inline GetROSWorldReferenceFrameIDResponse& operator=(GetROSWorldReferenceFrameIDResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const GetROSWorldReferenceFrameIDResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetROSWorldReferenceFrameIDResponse* internal_default_instance() {
    return reinterpret_cast<const GetROSWorldReferenceFrameIDResponse*>(
               &_GetROSWorldReferenceFrameIDResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  void Swap(GetROSWorldReferenceFrameIDResponse* other);
  friend void swap(GetROSWorldReferenceFrameIDResponse& a, GetROSWorldReferenceFrameIDResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetROSWorldReferenceFrameIDResponse* New() const final {
    return CreateMaybeMessage<GetROSWorldReferenceFrameIDResponse>(nullptr);
  }

  GetROSWorldReferenceFrameIDResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GetROSWorldReferenceFrameIDResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GetROSWorldReferenceFrameIDResponse& from);
  void MergeFrom(const GetROSWorldReferenceFrameIDResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetROSWorldReferenceFrameIDResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string world_reference_frame_id = 1;
  void clear_world_reference_frame_id();
  static const int kWorldReferenceFrameIdFieldNumber = 1;
  const ::std::string& world_reference_frame_id() const;
  void set_world_reference_frame_id(const ::std::string& value);
  #if LANG_CXX11
  void set_world_reference_frame_id(::std::string&& value);
  #endif
  void set_world_reference_frame_id(const char* value);
  void set_world_reference_frame_id(const char* value, size_t size);
  ::std::string* mutable_world_reference_frame_id();
  ::std::string* release_world_reference_frame_id();
  void set_allocated_world_reference_frame_id(::std::string* world_reference_frame_id);

  // @@protoc_insertion_point(class_scope:v1.agent.GetROSWorldReferenceFrameIDResponse)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr world_reference_frame_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protos_2fagent_2fv1_2fagent_2eproto;
};
// -------------------------------------------------------------------

class GetInterventionRequestRequest final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:v1.agent.GetInterventionRequestRequest) */ {
 public:
  GetInterventionRequestRequest();
  virtual ~GetInterventionRequestRequest();

  GetInterventionRequestRequest(const GetInterventionRequestRequest& from);

  inline GetInterventionRequestRequest& operator=(const GetInterventionRequestRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetInterventionRequestRequest(GetInterventionRequestRequest&& from) noexcept
    : GetInterventionRequestRequest() {
    *this = ::std::move(from);
  }

  inline GetInterventionRequestRequest& operator=(GetInterventionRequestRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const GetInterventionRequestRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetInterventionRequestRequest* internal_default_instance() {
    return reinterpret_cast<const GetInterventionRequestRequest*>(
               &_GetInterventionRequestRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  void Swap(GetInterventionRequestRequest* other);
  friend void swap(GetInterventionRequestRequest& a, GetInterventionRequestRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetInterventionRequestRequest* New() const final {
    return CreateMaybeMessage<GetInterventionRequestRequest>(nullptr);
  }

  GetInterventionRequestRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GetInterventionRequestRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GetInterventionRequestRequest& from);
  void MergeFrom(const GetInterventionRequestRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetInterventionRequestRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // @@protoc_insertion_point(class_scope:v1.agent.GetInterventionRequestRequest)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protos_2fagent_2fv1_2fagent_2eproto;
};
// -------------------------------------------------------------------

class GetInterventionResponseRequest final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:v1.agent.GetInterventionResponseRequest) */ {
 public:
  GetInterventionResponseRequest();
  virtual ~GetInterventionResponseRequest();

  GetInterventionResponseRequest(const GetInterventionResponseRequest& from);

  inline GetInterventionResponseRequest& operator=(const GetInterventionResponseRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetInterventionResponseRequest(GetInterventionResponseRequest&& from) noexcept
    : GetInterventionResponseRequest() {
    *this = ::std::move(from);
  }

  inline GetInterventionResponseRequest& operator=(GetInterventionResponseRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const GetInterventionResponseRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetInterventionResponseRequest* internal_default_instance() {
    return reinterpret_cast<const GetInterventionResponseRequest*>(
               &_GetInterventionResponseRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    10;

  void Swap(GetInterventionResponseRequest* other);
  friend void swap(GetInterventionResponseRequest& a, GetInterventionResponseRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetInterventionResponseRequest* New() const final {
    return CreateMaybeMessage<GetInterventionResponseRequest>(nullptr);
  }

  GetInterventionResponseRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GetInterventionResponseRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GetInterventionResponseRequest& from);
  void MergeFrom(const GetInterventionResponseRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetInterventionResponseRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string request_id = 1;
  void clear_request_id();
  static const int kRequestIdFieldNumber = 1;
  const ::std::string& request_id() const;
  void set_request_id(const ::std::string& value);
  #if LANG_CXX11
  void set_request_id(::std::string&& value);
  #endif
  void set_request_id(const char* value);
  void set_request_id(const char* value, size_t size);
  ::std::string* mutable_request_id();
  ::std::string* release_request_id();
  void set_allocated_request_id(::std::string* request_id);

  // @@protoc_insertion_point(class_scope:v1.agent.GetInterventionResponseRequest)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr request_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protos_2fagent_2fv1_2fagent_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// StreamDataResponse

// -------------------------------------------------------------------

// PostDataResponse

// -------------------------------------------------------------------

// RegisterROSTopicResponse

// -------------------------------------------------------------------

// GetROSTopicsRequest

// -------------------------------------------------------------------

// GetROSTopicsResponse

// repeated string topics = 1;
inline int GetROSTopicsResponse::topics_size() const {
  return topics_.size();
}
inline void GetROSTopicsResponse::clear_topics() {
  topics_.Clear();
}
inline const ::std::string& GetROSTopicsResponse::topics(int index) const {
  // @@protoc_insertion_point(field_get:v1.agent.GetROSTopicsResponse.topics)
  return topics_.Get(index);
}
inline ::std::string* GetROSTopicsResponse::mutable_topics(int index) {
  // @@protoc_insertion_point(field_mutable:v1.agent.GetROSTopicsResponse.topics)
  return topics_.Mutable(index);
}
inline void GetROSTopicsResponse::set_topics(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:v1.agent.GetROSTopicsResponse.topics)
  topics_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void GetROSTopicsResponse::set_topics(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:v1.agent.GetROSTopicsResponse.topics)
  topics_.Mutable(index)->assign(std::move(value));
}
#endif
inline void GetROSTopicsResponse::set_topics(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  topics_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:v1.agent.GetROSTopicsResponse.topics)
}
inline void GetROSTopicsResponse::set_topics(int index, const char* value, size_t size) {
  topics_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:v1.agent.GetROSTopicsResponse.topics)
}
inline ::std::string* GetROSTopicsResponse::add_topics() {
  // @@protoc_insertion_point(field_add_mutable:v1.agent.GetROSTopicsResponse.topics)
  return topics_.Add();
}
inline void GetROSTopicsResponse::add_topics(const ::std::string& value) {
  topics_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:v1.agent.GetROSTopicsResponse.topics)
}
#if LANG_CXX11
inline void GetROSTopicsResponse::add_topics(::std::string&& value) {
  topics_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:v1.agent.GetROSTopicsResponse.topics)
}
#endif
inline void GetROSTopicsResponse::add_topics(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  topics_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:v1.agent.GetROSTopicsResponse.topics)
}
inline void GetROSTopicsResponse::add_topics(const char* value, size_t size) {
  topics_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:v1.agent.GetROSTopicsResponse.topics)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
GetROSTopicsResponse::topics() const {
  // @@protoc_insertion_point(field_list:v1.agent.GetROSTopicsResponse.topics)
  return topics_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>*
GetROSTopicsResponse::mutable_topics() {
  // @@protoc_insertion_point(field_mutable_list:v1.agent.GetROSTopicsResponse.topics)
  return &topics_;
}

// -------------------------------------------------------------------

// GetROSTopicsSubscriptionConfigRequest

// -------------------------------------------------------------------

// GetROSTopicsSubscriptionConfigResponse

// repeated .v1.model.ROSTopicSubscriptionConfig topics = 1;
inline int GetROSTopicsSubscriptionConfigResponse::topics_size() const {
  return topics_.size();
}
inline ::v1::model::ROSTopicSubscriptionConfig* GetROSTopicsSubscriptionConfigResponse::mutable_topics(int index) {
  // @@protoc_insertion_point(field_mutable:v1.agent.GetROSTopicsSubscriptionConfigResponse.topics)
  return topics_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::v1::model::ROSTopicSubscriptionConfig >*
GetROSTopicsSubscriptionConfigResponse::mutable_topics() {
  // @@protoc_insertion_point(field_mutable_list:v1.agent.GetROSTopicsSubscriptionConfigResponse.topics)
  return &topics_;
}
inline const ::v1::model::ROSTopicSubscriptionConfig& GetROSTopicsSubscriptionConfigResponse::topics(int index) const {
  // @@protoc_insertion_point(field_get:v1.agent.GetROSTopicsSubscriptionConfigResponse.topics)
  return topics_.Get(index);
}
inline ::v1::model::ROSTopicSubscriptionConfig* GetROSTopicsSubscriptionConfigResponse::add_topics() {
  // @@protoc_insertion_point(field_add:v1.agent.GetROSTopicsSubscriptionConfigResponse.topics)
  return topics_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::v1::model::ROSTopicSubscriptionConfig >&
GetROSTopicsSubscriptionConfigResponse::topics() const {
  // @@protoc_insertion_point(field_list:v1.agent.GetROSTopicsSubscriptionConfigResponse.topics)
  return topics_;
}

// -------------------------------------------------------------------

// GetROSWorldReferenceFrameIDRequest

// -------------------------------------------------------------------

// GetROSWorldReferenceFrameIDResponse

// string world_reference_frame_id = 1;
inline void GetROSWorldReferenceFrameIDResponse::clear_world_reference_frame_id() {
  world_reference_frame_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GetROSWorldReferenceFrameIDResponse::world_reference_frame_id() const {
  // @@protoc_insertion_point(field_get:v1.agent.GetROSWorldReferenceFrameIDResponse.world_reference_frame_id)
  return world_reference_frame_id_.GetNoArena();
}
inline void GetROSWorldReferenceFrameIDResponse::set_world_reference_frame_id(const ::std::string& value) {
  
  world_reference_frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:v1.agent.GetROSWorldReferenceFrameIDResponse.world_reference_frame_id)
}
#if LANG_CXX11
inline void GetROSWorldReferenceFrameIDResponse::set_world_reference_frame_id(::std::string&& value) {
  
  world_reference_frame_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:v1.agent.GetROSWorldReferenceFrameIDResponse.world_reference_frame_id)
}
#endif
inline void GetROSWorldReferenceFrameIDResponse::set_world_reference_frame_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  world_reference_frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:v1.agent.GetROSWorldReferenceFrameIDResponse.world_reference_frame_id)
}
inline void GetROSWorldReferenceFrameIDResponse::set_world_reference_frame_id(const char* value, size_t size) {
  
  world_reference_frame_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:v1.agent.GetROSWorldReferenceFrameIDResponse.world_reference_frame_id)
}
inline ::std::string* GetROSWorldReferenceFrameIDResponse::mutable_world_reference_frame_id() {
  
  // @@protoc_insertion_point(field_mutable:v1.agent.GetROSWorldReferenceFrameIDResponse.world_reference_frame_id)
  return world_reference_frame_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GetROSWorldReferenceFrameIDResponse::release_world_reference_frame_id() {
  // @@protoc_insertion_point(field_release:v1.agent.GetROSWorldReferenceFrameIDResponse.world_reference_frame_id)
  
  return world_reference_frame_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetROSWorldReferenceFrameIDResponse::set_allocated_world_reference_frame_id(::std::string* world_reference_frame_id) {
  if (world_reference_frame_id != nullptr) {
    
  } else {
    
  }
  world_reference_frame_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), world_reference_frame_id);
  // @@protoc_insertion_point(field_set_allocated:v1.agent.GetROSWorldReferenceFrameIDResponse.world_reference_frame_id)
}

// -------------------------------------------------------------------

// GetInterventionRequestRequest

// string id = 1;
inline void GetInterventionRequestRequest::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GetInterventionRequestRequest::id() const {
  // @@protoc_insertion_point(field_get:v1.agent.GetInterventionRequestRequest.id)
  return id_.GetNoArena();
}
inline void GetInterventionRequestRequest::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:v1.agent.GetInterventionRequestRequest.id)
}
#if LANG_CXX11
inline void GetInterventionRequestRequest::set_id(::std::string&& value) {
  
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:v1.agent.GetInterventionRequestRequest.id)
}
#endif
inline void GetInterventionRequestRequest::set_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:v1.agent.GetInterventionRequestRequest.id)
}
inline void GetInterventionRequestRequest::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:v1.agent.GetInterventionRequestRequest.id)
}
inline ::std::string* GetInterventionRequestRequest::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:v1.agent.GetInterventionRequestRequest.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GetInterventionRequestRequest::release_id() {
  // @@protoc_insertion_point(field_release:v1.agent.GetInterventionRequestRequest.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetInterventionRequestRequest::set_allocated_id(::std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:v1.agent.GetInterventionRequestRequest.id)
}

// -------------------------------------------------------------------

// GetInterventionResponseRequest

// string request_id = 1;
inline void GetInterventionResponseRequest::clear_request_id() {
  request_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GetInterventionResponseRequest::request_id() const {
  // @@protoc_insertion_point(field_get:v1.agent.GetInterventionResponseRequest.request_id)
  return request_id_.GetNoArena();
}
inline void GetInterventionResponseRequest::set_request_id(const ::std::string& value) {
  
  request_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:v1.agent.GetInterventionResponseRequest.request_id)
}
#if LANG_CXX11
inline void GetInterventionResponseRequest::set_request_id(::std::string&& value) {
  
  request_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:v1.agent.GetInterventionResponseRequest.request_id)
}
#endif
inline void GetInterventionResponseRequest::set_request_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  request_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:v1.agent.GetInterventionResponseRequest.request_id)
}
inline void GetInterventionResponseRequest::set_request_id(const char* value, size_t size) {
  
  request_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:v1.agent.GetInterventionResponseRequest.request_id)
}
inline ::std::string* GetInterventionResponseRequest::mutable_request_id() {
  
  // @@protoc_insertion_point(field_mutable:v1.agent.GetInterventionResponseRequest.request_id)
  return request_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GetInterventionResponseRequest::release_request_id() {
  // @@protoc_insertion_point(field_release:v1.agent.GetInterventionResponseRequest.request_id)
  
  return request_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetInterventionResponseRequest::set_allocated_request_id(::std::string* request_id) {
  if (request_id != nullptr) {
    
  } else {
    
  }
  request_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), request_id);
  // @@protoc_insertion_point(field_set_allocated:v1.agent.GetInterventionResponseRequest.request_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace agent
}  // namespace v1

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_protos_2fagent_2fv1_2fagent_2eproto
