#!/usr/bin/env python

from __future__ import print_function

import formant
import rospy


def main():
    """Launch the Formant Bridge Node and spin forever. """
    try:
        rospy.init_node('formant_bridge_node')
        node = formant.BridgeNode()
        rospy.spin()
    except rospy.ROSInterruptException as e:
        print(e)
        pass


if __name__ == '__main__':
    main()
